---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: v1.configmaps
spec:
  additionalPrinterColumns:
  - jsonPath: .metadata.name
    name: Name
    type: string
  - jsonPath: .metadata.creationTimestamp
    name: Age
    type: date
  id: default-/v1/configmaps
